name: Deploy

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: sudo docker build -t 127.0.0.1:5000/azylla-dev:latest -f deploy/Dockerfile .

      - name: Push to local registry
        run: sudo docker push 127.0.0.1:5000/azylla-dev:latest

      - name: Deploy to Swarm
        run: sudo docker stack deploy -c deploy/docker-compose.yml azylla-dev
